import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets:['latin'], 
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--poppins-font"
})
const inter = Inter({
  subsets:['latin'], 
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--inter-font"
})


export const metadata = {
  title: "Blog App",
  description: "Generated by blog app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
